In [729]:
import numpy as np
arr = np.genfromtxt('orders.csv', delimiter=',', skip_header=1)	
np.zeros((3, 3)), np.ones((2, 4))
np.full((3, 3), 7)
np.eye(3)
np.linspace(0, 10, 5)
np.arange(0, 10, 2)
np.random.rand(3, 3), np.random.randn(3, 3)
np.random.randint(0, 10, size=(3, 3))

array([[2, 4, 6],
       [1, 2, 5],
       [9, 7, 4]])

In [739]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
shape = arr.shape 
arr.reshape(3, 3)
arr.flatten()
np.transpose(arr)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
np.concatenate((arr1, arr2), axis=0)
np.hstack((arr1, arr2)), np.vstack((arr1, arr2))

(array([[1, 2, 5, 6],
        [3, 4, 7, 8]]),
 array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]))

In [681]:
np.add(arr1,arr2) / np.subtract(arr1,arr2)
np.multiply(arr1,arr2) / np.divide(arr1,arr2)
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
np.dot(matrix1, matrix2)
np.sqrt(arr)
np.exp(arr1) / np.log(arr2)
np.power(arr, 2)
np.mean(arr), np.median(arr), np.std(arr)	
np.sum(arr, axis=0)

array([12, 15, 18])

In [682]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
arr[0], arr[1:3], arr[:, 1]	
arr[arr > 5]	
arr[[0, 2], [1, 3]]

array([ 2, 12])

In [683]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
np.sort(arr)
np.argsort(arr)
np.where(arr > 5)
np.unique(arr)
max_value = np.max(arr)
min_value = np.min(arr)
result = max_value / min_value
result

12.0

In [684]:
#Perform operations on arrays of different shapes.
arr + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [685]:
#Linear Algebra
import numpy as np
arr = np.array([[1, 2],
                [3, 4]])
np.linalg.inv(arr)
np.linalg.det(arr)
np.linalg.eig(arr)
np.linalg.norm(arr)
A = np.array([[3, 1], [1, 2]])
B = np.array([9, 8])
SOLUTION=np.linalg.solve(A,B)
SOLUTION

array([2., 3.])

In [686]:
#Data Preparation

np.clip(arr, a_min=0, a_max=10)
np.mean(arr) / np.std(arr)
normalized = (arr - np.mean(arr)) / np.std(arr)
normalized

array([[-1.34164079, -0.4472136 ],
       [ 0.4472136 ,  1.34164079]])

In [687]:
#Random Sampling
np.random.shuffle(arr)

In [731]:
np.save('data.npy', arr)
loaded = np.load('data.npy')
print(loaded)
load=np.savetxt('data.txt', arr, delimiter=',')
print(load)

ValueError: Cannot load file containing pickled data when allow_pickle=False

In [689]:
#PANDAS:

In [690]:
import pandas as pd
import numpy as np
df =pd.read_csv(r'C:\Users\Lenovo\Documents\ML\NUMPY AND PANDAS PRACTICE\reviews.csv')
is_null = df.isnull()       
not_null = df.notnull()    
df_filled = df.fillna(0)     
df_filled_mean = df.fillna(df.mean())
df_dropped = df.dropna(axis=0)  
df_interpolated = df.interpolate() 
df.fillna(value=999, inplace=True) 
print("Original DataFrame:")
print(df)
print("\nMissing Values (isnull):")
print(is_null)
print("\nDataFrame with Missing Values Filled (0):")
print(df_filled)
print("\nDataFrame with Missing Values Filled (Mean):")
print(df_filled_mean)
print("\nDataFrame with Missing Rows Dropped:")
print(df_dropped)
print("\nDataFrame with Interpolated Values:")
print(df_interpolated)


Original DataFrame:
   ReviewID  ProductID  CustomerID  Rating
0       301      201.0           1     5.0
1       302      202.0           3     4.0
2       303      203.0           2     3.0
3       304      204.0           5   999.0
4       305      999.0           4     5.0

Missing Values (isnull):
   ReviewID  ProductID  CustomerID  Rating
0     False      False       False   False
1     False      False       False   False
2     False      False       False   False
3     False      False       False    True
4     False       True       False   False

DataFrame with Missing Values Filled (0):
   ReviewID  ProductID  CustomerID  Rating
0       301      201.0           1     5.0
1       302      202.0           3     4.0
2       303      203.0           2     3.0
3       304      204.0           5     0.0
4       305        0.0           4     5.0

DataFrame with Missing Values Filled (Mean):
   ReviewID  ProductID  CustomerID  Rating
0       301      201.0           1    5.00
1    

In [691]:

df['ReviewID']
df[['ReviewID', 'ProductID']]
df.set_index('ReviewID', inplace=True)
df.loc[301]


ProductID     201.0
CustomerID      1.0
Rating          5.0
Name: 301, dtype: float64

In [692]:
import pandas as pd
import numpy as np
df =pd.read_csv(r'C:\Users\Lenovo\Documents\ML\NUMPY AND PANDAS PRACTICE\reviews.csv')
df['new_col'] = df['ReviewID'] + df['ProductID']
df['Age_group'] = pd.cut(df['Rating'], bins=3, labels=['Low', 'Medium', 'High'])
category_dummies =pd.get_dummies(df['CustomerID'])
df = pd.concat([df, category_dummies], axis=1)
print(df)


   ReviewID  ProductID  CustomerID  Rating  new_col Age_group      1      2  \
0       301      201.0           1     5.0    502.0      High   True  False   
1       302      202.0           3     4.0    504.0    Medium  False  False   
2       303      203.0           2     3.0    506.0       Low  False   True   
3       304      204.0           5     NaN    508.0       NaN  False  False   
4       305        NaN           4     5.0      NaN      High  False  False   

       3      4      5  
0  False  False  False  
1   True  False  False  
2  False  False  False  
3  False  False   True  
4  False   True  False  


In [693]:
df =pd.read_csv(r'C:\Users\Lenovo\Documents\ML\NUMPY AND PANDAS PRACTICE\reviews.csv')
df.groupby('CustomerID')['ReviewID'].sum()
df.agg({'Rating': 'mean', 'ProductID': 'sum'})
df.pivot_table(values='ProductID',index='Rating', aggfunc='sum')


ProductID
Rating           
3.0         203.0
4.0         202.0
5.0         201.0

In [694]:
import pandas as pd
df1 =pd.read_csv(r'C:\Users\Lenovo\Documents\ML\NUMPY AND PANDAS PRACTICE\customers.csv') 
df2 =pd.read_csv(r'C:\Users\Lenovo\Documents\ML\NUMPY AND PANDAS PRACTICE\orders.csv')
merged_inner = pd.merge(df1, df2, on='CustomerID', how='inner')
joined_left = df1.join(df2.set_index('CustomerID'), on='CustomerID', how='left')
concatenated = pd.concat([df1, df2], axis=0)
print("Merged DataFrame (Inner Join):")
print(merged_inner)
print("\nJoined DataFrame (Left Join):")
print(joined_left)
print("\nConcatenated DataFrame:")
print(concatenated)


Merged DataFrame (Inner Join):
   CustomerID     Name   Age         City  OrderID  Amount   OrderDate
0           1    Alice  25.0     New York      101   250.5  2024-12-20
1           2      Bob  30.0  Los Angeles      102   120.0  2024-12-21
2           3  Charlie  35.0          NaN      103   320.0  2024-12-22
3           4    David   NaN      Chicago      104     NaN  2024-12-23

Joined DataFrame (Left Join):
   CustomerID     Name   Age         City  OrderID  Amount   OrderDate
0           1    Alice  25.0     New York    101.0   250.5  2024-12-20
1           2      Bob  30.0  Los Angeles    102.0   120.0  2024-12-21
2           3  Charlie  35.0          NaN    103.0   320.0  2024-12-22
3           4    David   NaN      Chicago    104.0     NaN  2024-12-23
4           5      Eve  45.0      Houston      NaN     NaN         NaN

Concatenated DataFrame:
   CustomerID     Name   Age         City  OrderID  Amount   OrderDate
0         1.0    Alice  25.0     New York      NaN     NaN   

In [695]:
df.replace(np.nan, 400.00)
df.apply(lambda x: x.strip() if isinstance(x, str) else x)
df.drop_duplicates()
df

ReviewID  ProductID  CustomerID  Rating
0       301      201.0           1     5.0
1       302      202.0           3     4.0
2       303      203.0           2     3.0
3       304      204.0           5     NaN
4       305        NaN           4     5.0

In [696]:
df = pd.read_csv(r'C:\Users\Lenovo\Documents\ML\NUMPY AND PANDAS PRACTICE\products.csv')
df.pivot(index='ProductID', columns='ProductName', values='Price')
df.melt(id_vars=['Price'], value_vars=['ProductID', 'ProductName'])

Price     variable       value
0  1200.0    ProductID         201
1   800.0    ProductID         202
2   400.0    ProductID         203
3   200.0    ProductID         204
4     NaN    ProductID         205
5  1200.0  ProductName      Laptop
6   800.0  ProductName  Smartphone
7   400.0  ProductName      Tablet
8   200.0  ProductName     Monitor
9     NaN  ProductName    Keyboard

In [697]:
import pandas as pd
df = pd.read_csv(r'C:\Users\Lenovo\Documents\ML\NUMPY AND PANDAS PRACTICE\customers.csv')
description = df.describe()
numeric_df = df.select_dtypes(include=[float, int])
correlation = numeric_df.corr()
value_counts_col = df['CustomerID'].value_counts()
print("DataFrame Summary (Describe):")
print(description)
print("\nCorrelation Matrix:")
print(correlation)
print("\nValue Counts for 'Age':")
print(value_counts_col)


DataFrame Summary (Describe):
       CustomerID        Age
count    5.000000   4.000000
mean     3.000000  33.750000
std      1.581139   8.539126
min      1.000000  25.000000
25%      2.000000  28.750000
50%      3.000000  32.500000
75%      4.000000  37.500000
max      5.000000  45.000000

Correlation Matrix:
            CustomerID  Age
CustomerID         1.0  1.0
Age                1.0  1.0

Value Counts for 'Age':
CustomerID
1    1
2    1
3    1
4    1
5    1
Name: count, dtype: int64


In [698]:
import pandas as pd
df = pd.read_csv(r'C:\Users\Lenovo\Documents\ML\NUMPY AND PANDAS PRACTICE\reviews.csv')
df['col'] = (df['ReviewID'] - df['ReviewID'].mean()) / df['ReviewID'].std()
df['col'] = df['ReviewID'].apply(np.log1p)
print(df)

   ReviewID  ProductID  CustomerID  Rating       col
0       301      201.0           1     5.0  5.710427
1       302      202.0           3     4.0  5.713733
2       303      203.0           2     3.0  5.717028
3       304      204.0           5     NaN  5.720312
4       305        NaN           4     5.0  5.723585


In [699]:
import pandas as pd
df = pd.read_csv(r'C:\Users\Lenovo\Documents\ML\NUMPY AND PANDAS PRACTICE\orders.csv')
df['OrderDate'] = pd.to_datetime(df['OrderDate'])
df.set_index('OrderDate', inplace=True)
monthly_sum = df.resample('ME').sum()
print(monthly_sum)


            OrderID  CustomerID  Amount
OrderDate                              
2024-12-31      515        10.0  841.25


In [700]:
df.to_csv('orders.csv',index=False)
pd.read_csv('orders.csv')
df.to_excel('orders.xlsx',index=False)
df

OrderID  CustomerID  Amount
OrderDate                              
2024-12-20      101         1.0  250.50
2024-12-21      102         2.0  120.00
2024-12-22      103         3.0  320.00
2024-12-23      104         4.0     NaN
2024-12-24      105         NaN  150.75